// Package model contains the types for schema 'news'.
package model

// Code generated by xo. DO NOT EDIT.

func CaptchaByPhoneAndCode(db XODB, phone, code string) (*Captcha, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, phone, code ` +
		`FROM news.captcha ` +
		`WHERE phone = ? AND code = ?`

	// run query
	XOLog(sqlstr, phone, code)
	c := Captcha{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, phone, code).Scan(&c.ID, &c.Phone, &c.Code)
	if err != nil {
		return nil, err
	}

	return &c, nil
}

func CaptchaByPhone(db XODB, phone string) (*Captcha, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, phone, code ` +
		`FROM news.captcha ` +
		`WHERE phone = ?`

	// run query
	XOLog(sqlstr, phone)
	c := Captcha{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, phone).Scan(&c.ID, &c.Phone, &c.Code)
	if err != nil {
		return nil, err
	}

	return &c, nil
}

func (c *Captcha) InsertOrUpdate(db XODB, phone, code string) (*Captcha, error) {
	capt, _ := CaptchaByPhone(db, phone)
	if capt != nil {
		capt.Code.String = code
		capt.Update(db)
		return capt, nil
	} else {
		err := c.Insert(db)
		return capt, err
	}
}
