settings:
  legacy:
    force: false
    interval: 0s
server:
  status: false
  open: false
  port: 5002
  host: localhost
schema:
- name: news
  path: /Users/mj/go/src/github.com/dfang/yuanxin
  environment:
    APP_DB_USER: root
    APP_DB_NAME: news
  commands:
    clean:
      status: true
    test:
      status: true
    generate:
      status: true
    vet:
      status: true
    fmt:
      status: true
      args:
      - -s
      - -w
    build:
      status: true
      args:
        - -o news
    install:
      status: true
    run:
      status: true
  watcher:
    paths:
    - ./
    extensions:
    - go
    ignored_paths:
    - .idea
    - .git
    - .realize
    - vendor
