version: '3.1'

services:

  db:
    image: mysql
    container_name: db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: OC#oc2018
      MYSQL_ROOT_HOST: "%"

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080

  news:
    image: dfang/yuanxin:latest
    container_name: news
    links:
      - db
    ports:
      - 9090:9090

