version: '3.1'

services:

  db:
    image: mysql
    container_name: db
    restart: always
    ports:
      - 3306:3306
    environment:
      # MYSQL_ROOT_PASSWORD: OC#oc2018
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
    volumes:
     - ./db/mysql/data:/var/lib/mysql
     - ./db/mysql/log:/var/log/mysql
     - ./config/my.cnf:/etc/mysql/conf.d/my.cnf
     - ./init.d/:/docker-entrypoint-initdb.d/:ro

# #  adminer:
# #    image: adminer
# #    restart: always
# #    ports:
# #      - 9091:8080

  news:
    image: dfang/yuanxin:latest
    container_name: news
    restart: on-failure
    environment:
      APP_DB_USER: root
      APP_DB_PASSWORD: 
      APP_DB_HOST: tcp(db:3306)
      APP_DB_NAME: news
    links:
      - db:db
    ports:
      - 9090:9090
  
  gme:
    image: dfang/go-mysql-elasticsearch
    links:
      - elasticsearch:es
    depends_on:
      - db
      - elasticsearch
    volumes:
      # - ./config/river.toml:/go/src/github.com/siddontang/go-mysql-elasticsearch/river/etc/river.toml
      - ./config/river.toml:/go/etc/river.toml

  elasticsearch:
    image: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: kibana
    ports:
      - 5601:5601

